### ISSUE TITLE
Error, the flock command has to be in the command serach path.

### ISSUE THREAD

**Issue by jimbobjim123** [kcantrel/test-cf-waitingroom#1]
serach = search?
Any ideas how to get around?

**Comment by kcantrel** [comment]
That error message is saying that the scriopt can't find the flock command which is required to use the latest version of the simulate_requests script. If you are running on a Mac, which doesn't have the flock command, then you can use the previous version of the simulate_requests script that uses a different method of locking a file. It isn't as scalable as the flock method so I moved to the more pure Unix way.
